name: Create PR Automatically From Deployment to Main/Master

on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest

    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          pr_title: "Auto PR: From deployment Branch"
          pr_template: ".github/pull_request_template.md"
          pr_reviewer: "downey88"